$env:HF_HOME = "F:\huggingface\models"
$env:HF_HUB_CACHE = "F:\huggingface\models\hub"
$env:HUGGINGFACE_HUB_CACHE = "F:\huggingface\models\hub"
$env:TRANSFORMERS_CACHE = "F:\huggingface\models\hub"
$env:HF_ASSETS_CACHE = "F:\huggingface\models\assets"
$env:HF_XET_CACHE = "F:\huggingface\models\xet"
$env:TORCH_HOME = "F:\huggingface\models\torch"
$env:XDG_CACHE_HOME = "F:\huggingface\models\xdg_cache"
$env:PIP_CACHE_DIR = "F:\huggingface\models\pip_cache"
$env:CUDA_CACHE_PATH = "F:\huggingface\models\cuda_cache"
$env:TORCH_EXTENSIONS_DIR = "F:\huggingface\models\torch_extensions"
$env:TORCHINDUCTOR_CACHE_DIR = "F:\huggingface\models\torch_inductor"
$env:TRITON_CACHE_DIR = "F:\huggingface\models\triton"
$env:MPLCONFIGDIR = "F:\huggingface\models\matplotlib"
$env:NUMBA_CACHE_DIR = "F:\huggingface\models\numba_cache"
$env:TMP = "F:\projects\perchance_clone\perchance_clone\runtime\codex_temp"
$env:TEMP = "F:\projects\perchance_clone\perchance_clone\runtime\codex_temp"
$env:TMPDIR = "F:\projects\perchance_clone\perchance_clone\runtime\codex_temp"
$env:SQLITE_TMPDIR = "F:\projects\perchance_clone\perchance_clone\runtime\codex_temp"
$env:LOCALAPPDATA = "F:\projects\perchance_clone\perchance_clone\runtime\localappdata"
$env:OLLAMA_MODELS = "F:\ollama\models"
$env:PYTHONDONTWRITEBYTECODE = "1"
$env:COMPANION_PRELOAD_TEXT_MODEL = "1"
$env:COMPANION_PRELOAD_IMAGE_BACKEND = "1"
$env:COMPANION_STOP_OLLAMA_BEFORE_IMAGE = "1"

& "F:\anaconda3\envs\companion_v1\python.exe" -m uvicorn app.main:app --host 127.0.0.1 --port 8000
